language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
jobs:
  include:
    - stage: deploy
      deploy:
        provider: heroku
        api_key: $HEROKU_API_KEY
        app: $HEROKU_APP
on:
  branch: master
